### PR TITLE
Added support for Laravel 5.2

### LINKED ISSUE #32: Laravel 5.2 support
There is no more `Illuminate\Routing\Router::before` filter, it was deprecated in 5.1 and removed in 5.2. So `NewrelicServiceProvider::registerNamedTransactions` is broken.

### PR DESCRIPTION
**Pull request by apancutt**
Added support for Laravel 5.2. Fixes #32.

### CODE REVIEW

**Comment by pleckey** [comment]
:+1: will leave in `dev-master` until I can get a tagged version for 5.2 support out (as it breaks 5.0/5.1 support)

**Comment by stevethomas** [comment]
any chance you could please tag a version 2.0 release with this fix?

**Comment by pleckey** [comment]
@stevethomas yup, will do that today

**Comment by pleckey** [comment]
@stevethomas see https://github.com/In-Touch/laravel-newrelic/tree/2.1.0

Pushed as 2.1.0 so it doesn't break folks on the Laravel LTS, who can stay on 2.0.x

**Comment by stevethomas** [comment]
thanks @pleckey! Looking forward to integrating this package.

**Pull request merged**
