### PR TITLE
Add Lumen documentation to the README

### LINKED ISSUE #30: Lumen support
Do you have plan to support Lumen ?

Currently it does not work because of NewrelicServiceProvider and `$app['router']` usage.

### PR DESCRIPTION
**Pull request by Jalle19**
Closes #30 since this will document that you should not run what he tried to run (I tried too).

### CODE REVIEW

**Comment by Jalle19** [comment]
Preview: https://github.com/nordsoftware/laravel-newrelic/blob/483159cb6a1199a71bc4fdff06aa8c3116997bde/README.md

**Comment by Jalle19** [comment]
@pleckey ping

**Review by pleckey — CHANGES_REQUESTED** [review]
This has conflicts with the current `master` - if you can pull upstream and resolve the conflicts, I'll merge this.

**Comment by Jalle19** [comment]
@pleckey rebased

I'm not sure the instructions are correct anymore (they should be) since we resorted to writing https://github.com/nordsoftware/lumen-newrelic due to the lack of activity on this project.

**Comment by alfaproject** [comment]
What is the status of this?

**Pull request closed without merging**
